/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaeuro;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(App.getapi(), "Error!");
    }
}
